Repository lgehring/bl-predictor, pull requests merged in 2021-02, with the labels that each got.

#48 Evaluation step2
  bl_predictor/crawled_data.csv
  bl_predictor/models.py
  bl_predictor/prediction_evaluation.py
  setup.py
  tests/test_crawler+model_combo.py
  tests/test_evaluation.py
  tests/test_models.py
Labels: enhancement

#50 Evaluation step3
  Accuracy over time.png
  F1-score over time.png
  bl_predictor/prediction_evaluation.py
Labels: enhancement

#52 Evaluation 3x3 matrix
  bl_predictor/crawled_data.csv
  bl_predictor/models.py
  bl_predictor/prediction_evaluation.py
  plots/Accuracy over time.png
  plots/ConfMatrix BettingPoisson.png
  plots/ConfMatrix Frequency.png
  plots/ConfMatrix Poisson.png
  plots/F1-score over time.png
  tests/test_evaluation.py
Labels: enhancement

#56 Gui upgrade 1
  bl-predictor_logo.png
  bl_predictor/gui.py
  bl_predictor/gui_slider_widget.py
  setup.py
Labels: enhancement

#60 Gui tests
  .github/workflows/coverage.yml
  bl_predictor/crawled_data.csv
  bl_predictor/gui.py
  bl_predictor/gui_slider_widget.py
  tests/test_gui.py
Labels: enhancement

#61 Added separator between "Switch Theme" and "Exit" under _menu_bar.
  bl_predictor/gui.py
Labels: enhancement

#62 Final Bugfixes
  Accuracy over time.png
  F1-score over time.png
  bl_predictor/crawled_data.csv
  bl_predictor/gui.py
  bl_predictor/models.py
  bl_predictor/prediction_evaluation.py
  tests/test_crawler+model_combo.py
  tests/test_gui.py
  tests/test_models.py
Labels: bug

#63 Documentation/readme
  README.md
Labels: documentation
